FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libmagic1 \
    libfuzzy-dev \
    libssl-dev \
    build-essential \
    yara \
    libpango-1.0-0 \
    libpangoft2-1.0-0 \
    libharfbuzz0b \
    libfontconfig1 \
    libgdk-pixbuf-2.0-0 \
    libcairo2 \
    libcairo-gobject2 \
    fonts-liberation \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app/sentinelcore

COPY sentinelcore/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY sentinelcore/ .

ENV PYTHONPATH=/app/sentinelcore

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
